### ISSUE TITLE
Missing Cyber-Framework.py

### ISSUE THREAD

**Issue by raleighguevarra** [Cyber-Dioxide/Cyber-Sploit#4]
Trying to install as per instruction but getting these errors:

**Step 1:**
```
┌──(root㉿kali)-[~]
└─# git clone https://github.com/Cyber-Dioxide/Cyber-Sploit
```

**Step 2:**
```
┌──(root㉿kali)-[~/Cyber-Sploit]
└─# cd Cyber-Sploit     
```

**Step 3:**
```
┌──(root㉿kali)-[~/Cyber-Sploit]
└─# chmod +x *
```          

**Step 4:**
```
┌──(root㉿kali)-[~/Cyber-Sploit]
└─# bash install.sh   
```

[+] Launching Cyber-Sploit Framework.... /
python3: can't open file '/root/Cyber-Sploit/Cyber-Framework.py': [Errno 2] No such file or directory

**Step 5:**
```
┌──(root㉿kali)-[~/Cyber-Sploit]
└─# ./Cyber-Sploit.py 
```
import: Unable to open XServer ().
import: Unable to open XServer ().
./Cyber-Sploit.py: 3: from: not found
./Cyber-Sploit.py: 4: from: not found
./Cyber-Sploit.py: 5: from: not found
./Cyber-Sploit.py: 6: from: not found
import: Unable to open XServer ().
./Cyber-Sploit.py: 9: Syntax error: "(" unexpected

**PYTHON**
```
┌──(root㉿kali)-[~/Cyber-Sploit]
└─# python3 --version
```
Python 3.11.6

There is no Cyber-Framework.py file.

Thanks

**Comment by Cyber-Dioxide** [comment]
Thank you for reporting, i have checked again but our issues are very different and we both are running same python version. Install proper libraries, The code was coded back ion 2023 in python 3.9. I'm facing marshal decode error with 3.11. I'll take some steps to update the tool. Added in todo

**Comment by Cyber-Dioxide** [comment]
> Trying to install as per instruction but getting these errors:
> 
> **Step 1:**
> 
> ```
> ┌──(root㉿kali)-[~]
> └─# git clone https://github.com/Cyber-Dioxide/Cyber-Sploit
> ```
> 
> **Step 2:**
> 
> ```
> ┌──(root㉿kali)-[~/Cyber-Sploit]
> └─# cd Cyber-Sploit     
> ```
> 
> **Step 3:**
> 
> ```
> ┌──(root㉿kali)-[~/Cyber-Sploit]
> └─# chmod +x *
> ```
> 
> **Step 4:**
> 
> ```
> ┌──(root㉿kali)-[~/Cyber-Sploit]
> └─# bash install.sh   
> ```
> 
> [+] Launching Cyber-Sploit Framework.... / python3: can't open file '/root/Cyber-Sploit/Cyber-Framework.py': [Errno 2] No such file or directory
> 
> **Step 5:**
> 
> ```
> ┌──(root㉿kali)-[~/Cyber-Sploit]
> └─# ./Cyber-Sploit.py 
> ```
> 
> import: Unable to open XServer (). import: Unable to open XServer (). ./Cyber-Sploit.py: 3: from: not found ./Cyber-Sploit.py: 4: from: not found ./Cyber-Sploit.py: 5: from: not found ./Cyber-Sploit.py: 6: from: not found import: Unable to open XServer (). ./Cyber-Sploit.py: 9: Syntax error: "(" unexpected
> 
> **PYTHON**
> 
> ```
> ┌──(root㉿kali)-[~/Cyber-Sploit]
> └─# python3 --version
> ```
> 
> Python 3.11.6
> 
> There is no Cyber-Framework.py file.
> 
> Thanks

**Comment by Cyber-Dioxide** [comment]
and btw its python3 Cyber-Sploit.py not Cuber-Framework.py

**Comment by Cyber-Dioxide** [comment]
This issue has been closed, as it works on Windows and Linux now, but not recommended to be used on Windows.
